// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Phone struct {
	ID          int32         `json:"id"`
	UserID      sql.NullInt32 `json:"user_id"`
	PhoneNumber string        `json:"phone_number"`
	CreatedAt   sql.NullTime  `json:"created_at"`
}

type User struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	Email     string       `json:"email"`
	CreatedAt sql.NullTime `json:"created_at"`
}
