// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: phone.sql

package db

import (
	"context"
	"database/sql"
)

const createPhone = `-- name: CreatePhone :one
INSERT INTO phones (user_id, phone_number)
VALUES ($1, $2)
RETURNING id, user_id, phone_number, created_at
`

type CreatePhoneParams struct {
	UserID      sql.NullInt32 `json:"user_id"`
	PhoneNumber string        `json:"phone_number"`
}

func (q *Queries) CreatePhone(ctx context.Context, arg CreatePhoneParams) (Phone, error) {
	row := q.db.QueryRowContext(ctx, createPhone, arg.UserID, arg.PhoneNumber)
	var i Phone
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PhoneNumber,
		&i.CreatedAt,
	)
	return i, err
}

const deletePhone = `-- name: DeletePhone :exec
DELETE FROM phones
WHERE user_id = $1
`

func (q *Queries) DeletePhone(ctx context.Context, userID sql.NullInt32) error {
	_, err := q.db.ExecContext(ctx, deletePhone, userID)
	return err
}

const getPhone = `-- name: GetPhone :one
SELECT id, user_id, phone_number, created_at FROM phones
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetPhone(ctx context.Context, userID sql.NullInt32) (Phone, error) {
	row := q.db.QueryRowContext(ctx, getPhone, userID)
	var i Phone
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PhoneNumber,
		&i.CreatedAt,
	)
	return i, err
}

const updatePhone = `-- name: UpdatePhone :one
UPDATE phones
SET phone_number = $2
WHERE user_id = $1
RETURNING id, user_id, phone_number, created_at
`

type UpdatePhoneParams struct {
	UserID      sql.NullInt32 `json:"user_id"`
	PhoneNumber string        `json:"phone_number"`
}

func (q *Queries) UpdatePhone(ctx context.Context, arg UpdatePhoneParams) (Phone, error) {
	row := q.db.QueryRowContext(ctx, updatePhone, arg.UserID, arg.PhoneNumber)
	var i Phone
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PhoneNumber,
		&i.CreatedAt,
	)
	return i, err
}
