// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreatePhone(ctx context.Context, arg CreatePhoneParams) (Phone, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePhone(ctx context.Context, userID sql.NullInt32) error
	DeleteUser(ctx context.Context, id int32) error
	GetPhone(ctx context.Context, userID sql.NullInt32) (Phone, error)
	GetUser(ctx context.Context, id int32) (User, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdatePhone(ctx context.Context, arg UpdatePhoneParams) (Phone, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error)
}

var _ Querier = (*Queries)(nil)
